[versions]
agp = "8.13.1"
hiddenapibypass = "6.1"

[libraries]
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

